version: '3.8'

services:
  app:
    build:
      context: ./app
    image: blog-app-app:latest
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
    image: blog-app-server:latest
    ports:
      - "4000:4000"
