import CreateBlog from '@/Layout/Components/CreateBlog'
import { Metadata } from 'next'
export const metadata: Metadata = {
    title: "CrateBlog || blogup",
    description: "Generated by create next app",
  };
function Page() {
    return (
        <CreateBlog />
    )
}

export default Page