import { axiosInstance } from '@/Axios/config'
import BlogsGroup from '@/Layout/Components/BlogsGroup'
import React from 'react'
import { Metadata } from 'next'
export const metadata: Metadata = {
    title: "Blogs || blogup",
    description: "Generated by create next app",
};
async function Page() {
    const response = await axiosInstance.get("/blog")
    const { BlogPost } = response.data
    return (
        <div className="p-6 min-h-screen">
            <BlogsGroup BlogPost={BlogPost} />
        </div>
    )


}

export default Page