import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UseReduxprovider } from "@/Redux/store";
import Navbar from "@/Layout/UI/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "blog app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UseReduxprovider>
          <Navbar />
          {children}
        </UseReduxprovider>
      </body>
    </html>
  );
}
