import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Layout/ui/Navbar";
import { UseReduxprovider } from "@/Redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "blog app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}
        <UseReduxprovider>
          <Navbar />
          {children}

        </UseReduxprovider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
