import Loading from "@/UI/loading";
import React from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "loading || blogup",
  description: "Generated by create next app",
};
const Page: React.FC = () => {
  return <Loading />;
};

export default Page;
