name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged
        ports:
          - 3000:3000
          - 4000:4000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ashutosh136 }}
        password: ${{ secrets.2004@#asH }}

    - name: Build and push app image
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up -d

    - name: Push Docker images
      run: |
        docker tag blog-app-app:latest ${{ secrets.ashutosh136 }}/blog-app-app:latest
        docker tag blog-app-server:latest ${{ secrets.ashutosh136 }}/blog-app-server:latest
        docker push ${{ secrets.ashutosh136 }}/blog-app-app:latest
        docker push ${{ secrets.ashutosh136 }}/blog-app-server:latest

    - name: Deploy to production
      run: |
        ssh -o StrictHostKeyChecking=no user@yourserver.com "cd /path/to/app && docker-compose down && docker-compose pull && docker-compose up -d"

